# Generated by Django 2.0 on 2020-04-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_centre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Agent_centre',
            },
        ),
        migrations.CreateModel(
            name='Agent_sanitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_agent', models.CharField(max_length=50)),
                ('prenom_agent', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('etat', models.CharField(max_length=20)),
                ('profil', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Agent_sanitaire',
            },
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Allergie',
            },
        ),
        migrations.CreateModel(
            name='Centre_sanitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_centre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Centre_sanitaire',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_commune', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'commune',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('traitement', models.TextField()),
                ('agent_centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_centre')),
            ],
            options={
                'db_table': 'Consultation',
            },
        ),
        migrations.CreateModel(
            name='Groupe_sanguin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'Groupe_sanguin',
                'ordering': ['groupe'],
            },
        ),
        migrations.CreateModel(
            name='Maladie_chronique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_maladie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Maladie_chronique',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pat', models.CharField(max_length=50)),
                ('prenom_pat', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('groupe_sanguin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Groupe_sanguin')),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Patient_allergie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Allergie')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Patient')),
            ],
            options={
                'db_table': 'Patient_allergie',
            },
        ),
        migrations.CreateModel(
            name='Patient_chronique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie_chronique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Maladie_chronique')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Patient')),
            ],
            options={
                'db_table': 'Patient_chronique',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_province', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Province',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_zone', models.CharField(max_length=50)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Commune')),
            ],
            options={
                'db_table': 'Zone',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Zone'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Patient'),
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Province'),
        ),
        migrations.AddField(
            model_name='agent_centre',
            name='agent_sanitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_sanitaire'),
        ),
        migrations.AddField(
            model_name='agent_centre',
            name='centre_sanitaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Centre_sanitaire'),
        ),
    ]
