# Generated by Django 2.0 on 2020-04-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='Groupe_sanguin',
        ),
    ]
