# Generated by Django 2.0 on 2020-04-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0002_auto_20200420_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent_centre',
            name='agent_sanitaire',
        ),
        migrations.DeleteModel(
            name='Agent_sanitaire',
        ),
    ]
