# Generated by Django 2.0 on 2020-04-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0005_agent_centre_consultation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent_sanitaire',
            table='Agent_sanitaire',
        ),
    ]
