# Generated by Django 2.0 on 2020-04-29 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0006_auto_20200422_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_allergie',
            name='agent_centre',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_centre'),
        ),
        migrations.AddField(
            model_name='patient_chronique',
            name='agent_centre',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_centre'),
        ),
    ]
