# Generated by Django 2.0 on 2020-04-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0007_auto_20200429_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_allergie',
            name='agent_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_centre'),
        ),
        migrations.AlterField(
            model_name='patient_chronique',
            name='agent_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salvarApp.Agent_centre'),
        ),
    ]
