# Generated by Django 2.0 on 2020-04-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salvarApp', '0008_auto_20200429_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='traitement',
            field=models.TextField(default='Pas des traitements en cours'),
        ),
    ]
